name: readthedocs
channels:
  - conda-forge
dependencies:
  - python=3.13
  - gxx_linux-64
  - icu=73.2
  - cmake
  - ninja
  - hdf5
  - libxml2=2.13.9
  - swig=4.4.1
  - catch2
  - unittest-xml-reporting
  - doxygen
  - Sphinx=6.2.1
  - numpydoc
  - breathe
  - myst-parser
  - sphinx-automodapi
  - graphviz
