name: readthedocs
channels:
  - conda-forge
dependencies:
  - python=3.13
  - gxx_linux-64=14.3.0
  - cmake
  - ninja
  - hdf5-static
  - libxml2
  - swig
  - catch2
  - unittest-xml-reporting
  - doxygen
  - Sphinx=6.2.1
  - numpydoc
  - breathe
  - myst-parser
  - sphinx-automodapi
  - graphviz
